apiVersion: rafay.io/v1alpha1
kind: Cluster
metadata:
  name: azurecluster
  project: poc
spec:
  type: aks
  blueprint: default-aks
  cloudprovider: azure-cloud-credential
  clusterConfig:
    apiVersion: rafay.io/v1alpha1
    kind: aksClusterConfig
    metadata:
      name: azurecluster
    spec:
      resourceGroupName: azureresourcegroup
      managedCluster:
        type: Microsoft.ContainerService/managedClusters
        apiVersion: "2021-05-01"
        location: azureregion
        identity:
          type: SystemAssigned
        properties:
          dnsPrefix: my-cluster-dns
          kubernetesVersion: 1.21.14
      nodePools:
      - type: Microsoft.ContainerService/managedClusters/agentPools
        apiVersion: "2021-05-01"
        location: azureregion
        name: agentpooly
        properties:
          count: 1
          maxPods: 40
          mode: System
          vmSize: Standard_DS3_v2
